routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('vehicles' , 'VehicleController');
Route::resource('vehicleModels', 'VehicleModelController');
Route::resource('vehicleTypes', 'VehicleTypeController');
Route::resource('vehicleBrands', 'VehicleBrandController');
Route::resource('vehicleColors', 'VehicleColorController');
Route::resource('vehicleUsers', 'UserForVehicleController');

app/VehicleBrand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VehicleBrand extends Model
{
    protected $fillable =[
      'vehicle_brand'
    ];

    public function models()
    {
        return $this->hasMany(VehicleModel::class);
    }
}

app/Http/Controllers/VehicleBrandController.php
<?php

namespace App\Http\Controllers;

use App\VehicleBrand;
use App\VehicleModel;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class VehicleBrandController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicleBrands = VehicleBrand::all();
        return view('vehicleBrands.index', compact('vehicleBrands'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vehicleBrands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'vehicle_brand' => 'required|unique:vehicle_brands,vehicle_brand'
        ]);

        VehicleBrand::create([
            'vehicle_brand' => strtoupper(request('vehicle_brand'))
        ]);

        return redirect()->route('vehicleBrands.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehicleBrand = VehicleBrand::find($id);
        $vehicleModels = VehicleModel::all();
        return view('vehicleBrands.show', compact('vehicleBrand', 'vehicleModels'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicleBrand = VehicleBrand::find($id);
        return view('vehicleBrands.edit', compact('vehicleBrand'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'vehicle_brand' => 'required|unique:vehicle_brands,vehicle_brand'
        ]);

        $vehicle = VehicleBrand::find($id);
        $vehicle->vehicle_brand = strtoupper(request('vehicle_brand'));

        $vehicle->save();


        return redirect()->route('vehicleBrands.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            VehicleBrand::find($id)->delete();
        } catch (QueryException $e) {
            $message = "This model is using by another table. You can't delete this model.";
            return back()->with('error', $message);
        }
        return redirect()->route('vehicleBrands.index', compact('text'));
    }
}

resources/views/vehicleBrands/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add New Vehicle Brand</div>



                    <div class="card-body">
                        <form action="{{route('vehicleBrands.store')}}" method="post">
                            @csrf

                            <div class="form-group">
                                <label for="brand">Vehicle Brand</label>
                                <input type="text" style="text-transform: uppercase;"  class="form-control @error('vehicle_brand') is-invalid @enderror" id="brand"
                                       name="vehicle_brand" value="{{old('vehicle_brand')}}" placeholder="example: BMW, AUDI, MERCEDES">
                                @error('vehicle_brand')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-primary">Add</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vehicleBrands/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Vehicle Brand Name</div>

                    @if($errors->count())
                        @foreach ($errors->all() as $error)
                            <div class="text-danger text-right">{{ $error }}</div>
                        @endforeach
                    @endif

                </div>
                <div class="card-body">
                    <form action="/vehicleBrands/{{$vehicleBrand->id}}" method="post">
                        @method('PATCH')
                        @csrf

                        <div class="container">
                            <div class="form-group">
                                <label for="brand">Brand Name</label>
                                <input type="text" class="form-control @error('brand') is-invalid @enderror" id="brand"
                                       name="vehicle_brand" value="{{$vehicleBrand->vehicle_brand}}">
                                @error('brand')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                            <button type="submit" class="btn btn-primary">Update</button>
                            <a class="btn btn-primary" href="http://carautomation.test/vehicleBrands/" role="button">Cancel</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/vehicleBrands/index.blade.php
@extends('layouts.app')

@section('content')
    @isset($text)
        <p>{{$text}}</p>
    @endisset
    <div class="container">
        <div class="card">
            <table id="myTable" class="display dataTable" style="width: 100%" role="grid">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Vehicle Brands</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($vehicleBrands as $brand)
                    <tr>
                        <th scope="row"><a href="/vehicleBrands/{{$brand->id}}">{{$brand->id}}</a></th>
                        <td><a href="/vehicleBrands/{{$brand->id}}">{{$brand->vehicle_brand}}</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/vehicleBrands/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card bg-light mb-3" style="max-width: 18rem;">
            <h3 class="card-header" style="text-align: center">{{$vehicleBrand->vehicle_brand}}</h3>
            <div class="card-body">
                <form action="/vehicleBrands/{{$vehicleBrand->id}}/edit" method="get">
                @csrf
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
            <form action="/vehicleBrands/{{$vehicleBrand->id}}" method="post">
            @method('DELETE')
            @csrf
            <!-- Button trigger modal -->
                <button type="button" class="btn btn-dark" data-toggle="modal"
                        data-target="#deleteModal">
                    Delete
                </button>
                <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                     aria-labelledby="eminMi" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="eminMi">Are You Sure?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                </button>
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            </form>
        </div>
    </div>

@endsection