routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('vehicles' , 'VehicleController');
Route::resource('vehicleModels', 'VehicleModelController');
Route::resource('vehicleTypes', 'VehicleTypeController');
Route::resource('vehicleBrands', 'VehicleBrandController');
Route::resource('vehicleColors', 'VehicleColorController');
Route::resource('vehicleUsers', 'UserForVehicleController');

resources/views/vehicleUsers/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add New User</div>


                    <div class="card-body">
                        <form action="{{route('vehicleUsers.store')}}" method="post" enctype="multipart/form-data">
                            @csrf


                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text"
                                       value="{{old('name')}}"
                                       class="form-control @error('name') is-invalid @enderror" id="name"
                                       name="name" required autocomplete="name" autofocus>
                                @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="email">E-Mail</label>
                                <input type="text"
                                       value="{{old('email')}}"
                                       class="form-control @error('email') is-invalid @enderror"
                                       id="email" name="email" required autocomplete="email">
                                @error('email')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="password">Password</label>
                                <input id="password" type="password"
                                       class="form-control @error('password') is-invalid @enderror" name="password"
                                       required autocomplete="new-password">

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="password-confirm"
                                       class="col-form-label text-md-right">{{ __('Confirm Password') }}</label>


                                <input id="password-confirm" type="password" class="form-control"
                                       name="password_confirmation" required autocomplete="new-password">
                            </div>

                            <fieldset class="form-group">
                                <div class="row">
                                    <legend class="col-form-label col-sm-2 pt-0 text-nowrap">User Status</legend>
                                    <div class="col-sm-10">
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="status" id="gridRadios1"
                                                   value="active" checked>
                                            <label class="form-check-label" for="gridRadios1">
                                                Active
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="status" id="gridRadios2"
                                                   value="inactive">
                                            <label class="form-check-label" for="gridRadios2">
                                                Inactive
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>

                            <div class="form-group">
                                <label for="img">image file</label>
                                <input type="file" class="form-control @error('img') is-invalid @enderror" id="img"
                                       name="img">
                            </div>


                            <button type="submit" class="btn btn-primary">Add</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vehicleUsers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit User</div>
                    <div class="container">
                        <label for="user">User Name</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                               name="name" value="{{$user->name}}" disabled>
                        @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="card-body">
                        <form action="/vehicleUsers/{{$user->id}}" method="post" enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            <div class="form-group">
                                <label for="newName">New User Name</label>
                                <input type="text" class="form-control" id="newName" name="name"
                                       value="{{$user->name}}">
                            </div>

                            <fieldset class="form-group">
                                <div class="row">
                                    <legend class="col-form-label col-sm-2 pt-0 text-nowrap">User Status</legend>
                                    <div class="col-sm-10">
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="status" id="gridRadios1"
                                                   value="active" checked>
                                            <label class="form-check-label" for="gridRadios1">
                                                Active
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="radio" name="status" id="gridRadios2"
                                                   value="inactive">
                                            <label class="form-check-label" for="gridRadios2">
                                                Inactive
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>

                            <div class="form-group">
                                <label for="img">image file</label>
                                <input type="file" class="form-control @error('img') is-invalid @enderror" id="img"
                                       name="img">
                            </div>

                            <button type="submit" class="btn btn-primary">Update</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vehicleUsers/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .green {
            color: green;
            font-weight: bold;
        }

        .red {
            color: red;
            font-weight: bold;
        }
    </style>
    <div class="container">
        <div class="card">
            <table id="myTable" class="display dataTable" style="width: 100%" role="grid">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">User</th>
                    <th scope="col">Email</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($users as $user)
                    <tr>
                        <th scope="row"><a href="/vehicleUsers/{{$user->id}}">{{$user->id}}</a></th>
                        <td><a href="/vehicleUsers/{{$user->id}}">{{$user->name}}</a></td>
                        <td>{{$user->email}}</td>
                        <td class="{{$user->status == 'Active' ? 'red' : 'green'}}">{{$user->status ? 'Active' : 'Inactive'}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/vehicleUsers/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card bg-light mb-3" style="max-width: 18rem;">
            <h3 class="card-header" style="text-align: center">{{$user->name}}</h3>
            <div class="card-body">
                <form action="/vehicleUsers/{{$user->id}}/edit" method="get">
                @csrf
                    <img src="{{$user->img}}" class="card-img-top">
                <div style="text-align: center">{{$user->status ? 'Active' : 'Inactive' }}</div>
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
            <form action="/vehicleUsers/{{$user->id}}" method="post">
            @method('DELETE')
            @csrf
            <!-- Button trigger modal -->
                <button type="button" class="btn btn-dark" data-toggle="modal"
                        data-target="#deleteModal">
                    Delete
                </button>
                <!-- Modal -->
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                     aria-labelledby="eminMi" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="eminMi">Are You Sure?</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                </button>
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            </form>
        </div>
    </div>

@endsection