routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('vehicles' , 'VehicleController');
Route::resource('vehicleModels', 'VehicleModelController');
Route::resource('vehicleTypes', 'VehicleTypeController');
Route::resource('vehicleBrands', 'VehicleBrandController');
Route::resource('vehicleColors', 'VehicleColorController');
Route::resource('vehicleUsers', 'UserForVehicleController');

app/VehicleModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class VehicleModel extends Model
{

    protected $fillable = [
        'model',
        'model_year',
        'vehicle_brand_id',
        'img'
    ];

    public function vehicleBrand()
    {
        return $this->belongsTo(VehicleBrand::class, 'vehicle_brand_id');
    }

    public function vehicles()
    {
        return $this->hasMany(Vehicle::class);
    }

    public function getUrlPath()
    {
        return Storage::url($this->path);
    }
}

app/Http/Controllers/VehicleModelController.php
<?php

namespace App\Http\Controllers;

use App\Vehicle;
use App\VehicleBrand;
use App\VehicleModel;
use Illuminate\Http\Request;
use Illuminate\Database\QueryException;

class VehicleModelController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicleModels = VehicleModel::all();

        return view('vehicleModels.index', compact('vehicleModels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vehicles = VehicleBrand::all();
        return view('vehicleModels.create', compact('vehicles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $request->validate([
            'model' => 'required|unique:vehicle_models,model',
            'model_year' => 'required|Integer|date_format:Y',
            'vehicle_brand_id' => 'required|integer|exists:vehicle_brands,id',
            'img' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        $img = $request->file('img');
        $img->store('public/images');
        $url = $img->hashName('/images');


        VehicleModel::create([
            'model' => strtoupper(request('model')),
            'model_year' => request('model_year'),
            'vehicle_brand_id' => request('vehicle_brand_id'),
            'img' => $url
        ]);



        return redirect()->route('vehicleModels.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehicleModel = VehicleModel::find($id);
        return view('vehicleModels.show', compact('vehicleModel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicles = VehicleBrand::all();
        $vehicleModel = VehicleModel::find($id);
        return view('vehicleModels.edit', compact('vehicleModel','vehicles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'model' => 'required',
            'model_year' => 'required|Integer|date_format:Y',
            'vehicle_brand_id' => 'required|integer|exists:vehicle_brands,id',
        ]);

        if ($request->file('img')) {
            $img = $request->file('img');
            $img->store('public/images');
            $url = $img->hashName('/images');
        }

        $vehicle = VehicleModel::find($id);
        $vehicle->model = strtoupper(request('model'));
        $vehicle->model_year = request('model_year');
        $vehicle->vehicle_brand_id = request('vehicle_brand_id');
        $vehicle->img = $url;
        $vehicle->save();




        return redirect()->route('vehicleModels.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            VehicleModel::find($id)->delete();
        } catch (QueryException $e) {
            $message = "This model is using by another table. You can't delete this model.";
            return back()->with('error', $message);
        }

        return redirect()->route('vehicleModels.index');
    }
}

resources/views/vehicleModels/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add New Vehicle Model</div>



                    <div class="card-body">
                        <form action="{{route('vehicleModels.store')}}" method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group">
                                <label for="model">Vehicle Model</label>
                                <input type="text" style="text-transform: uppercase;"  class="form-control @error('model') is-invalid @enderror" id="model"
                                       name="model" value="{{old('model')}}" placeholder="example: RX8, TT, A100">
                                @error('model')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="modelYear">Model Year</label>
                                <input type="text" style="text-transform: uppercase;"  class="form-control @error('model_year') is-invalid @enderror" id="modelYear"
                                       name="model_year" value="{{old('model_year')}}" placeholder="example: 1996, 2005, 2019">
                                @error('model_year')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="img">image file</label>
                                <input type="file" class="form-control"
                                       id="img"
                                       name="img">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlSelect1">Select Brand</label>
                                <select class="my-select2 form-control @error('vehicle_brand_id') is-invalid @enderror" id="exampleFormControlSelect1" name="vehicle_brand_id">
                                    <option selected>Choose One</option>
                                    @foreach ($vehicles as $vehicle)
                                        <option value="{{$vehicle->id}}">{{$vehicle->vehicle_brand}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary">Add</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vehicleModels/edit.blade.php
@extends('layouts.app')



    <div class="container">
        @section('content')
            @if($errors->count())
                @foreach ($errors->all() as $error)
                    <div class="text-danger text-right">{{ $error }}</div>
                @endforeach
            @endif
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Vehicle Model Name</div>

                    <div class="card-body">
                        <div class="container">
                            <form action="/vehicleModels/{{$vehicleModel->id}}" method="post"
                                  enctype="multipart/form-data">
                                @method('PATCH')
                                @csrf

                                <div class="form-group">
                                    <label for="model">Model Name</label>
                                    <input type="text" class="form-control @error('model') is-invalid @enderror"
                                           id="model"
                                           name="model" value="{{$vehicleModel->model}}">
                                    @error('model')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="year">Model Year</label>
                                    <input type="text" class="form-control @error('year') is-invalid @enderror"
                                           id="year"
                                           name="model_year" value="{{$vehicleModel->model_year}}">
                                    @error('year')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="img">image file</label>
                                    <input type="file" class="form-control @error('model_year') is-invalid @enderror"
                                           id="img"
                                           name="img"
                                           >
                                </div>
                                <div class="form-group">
                                    <label for="exampleFormControlSelect1">Select Brand</label>
                                    <select
                                        class="my-select2 form-control @error('vehicle_brand_id') is-invalid @enderror"
                                        id="exampleFormControlSelect1" name="vehicle_brand_id">
                                        <option selected>{{$vehicleModel->vehicleBrand->vehicle_brand}}</option>
                                        @foreach ($vehicles as $vehicle)
                                            <option value="{{$vehicle->id}}">{{$vehicle->vehicle_brand}}</option>
                                        @endforeach
                                    </select>
                                </div>



                                <button type="submit" class="btn btn-primary">Update</button>

                                <a class="btn btn-primary" href="http://carautomation.test/vehicleModels/"
                                   role="button">Cancel
                                </a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/vehicleModels/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card-columns">
            @foreach($vehicleModels as $model)
                <div class="card">
                    @isset($model->img)
                        <img src="{{$model->img}}" class="card-img-top" alt="...">
                    @endisset
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="/vehicleModels/{{$model->id}}">{{$model->model}}</a>
                        </h5>
                        <p class="card-text">{{$model->vehicleBrand->vehicle_brand}} {{$model->model}} is available now. It can be used by chosen drivers.</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Model Year: {{$model->model_year}}</small>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/vehicleModels/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form action="/vehicleModels/{{$vehicleModel->id}}/edit" method="get">
            @csrf
            <div class="card" style="width: 18rem;">
                <img src="{{$vehicleModel->img}}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">
                        Model: {{$vehicleModel->model}} {{$vehicleModel->vehicleBrand->vehicle_brand}}</h5>
                    <p class="card-text">This vehicles are using for specific clients, our transporter Jason Statham
                        drives safe</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">This car models year is {{$vehicleModel->model_year}}</li>
                </ul>

                <button type="submit" class="btn btn-primary">Edit</button>


                <form action="/vehicleModels/{{$vehicleModel->id}}" method="post">
                @method('DELETE')
                @csrf
                <!-- Button trigger modal -->
                    <button type="button" class="btn btn-dark" data-toggle="modal"
                            data-target="#deleteModal">
                        Delete
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                         aria-labelledby="eminMi" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="eminMi">Are You Sure?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close
                                    </button>
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </form>
    </div>



@endsection